### ISSUE TITLE
Бага с группой.

### ISSUE THREAD

**Issue by op-hui** [op-hui/mu2ch#105]
По словам анона:

"Я был лидером группы. Прот попросился ко мне в группу. Я отвел его с собой домой к себе, завел в сортир и дропнул его там. Он нажал "назад" и полетел в лекторий с вещами. Я провел то же самое меня не кикнуло"

**Comment by copyright2015** [comment]
пофиксил баг. move_to(caller,quiet=True) когда quiet тру - не вызываеются хуки announce_move_to, announce_move_from

**Comment by copyright2015** [comment]
команда назад использует эти хуки для записи предыдущей локации
