### ISSUE TITLE
Хата анона и общий коридор

### ISSUE THREAD

**Issue by op-hui** [op-hui/mu2ch#15]
Сделать фильтр на список выходов из Коридора.
В данный момент игрок видит столько выходов в Прихожую, сколько есть хат.

Сейчас это выглядит так:

```
Коридор
Общая локация
Exits: Прихожка, Прихожка, Прихожка, Прихожка, Прихожка, Прихожка, Прихожка, Прихожка, Прихожка,
Прихожка, Прихожка, Прихожка, Прихожка, Прихожка, Прихожка, Прихожка, Прихожка, Прихожка,
Прихожка, Прихожка, Прихожка, Прихожка, Прихожка, Прихожка, Прихожка, Прихожка, Прихожка,
Прихожка, Прихожка, Прихожка, Прихожка, Прихожка, Прихожка, Прихожка, Прихожка, Прихожка
You see: box
```

для комнаты at_appearance нужно переопределить хук и фильтровать выходы

**Comment by copyright2015** [comment]
может сделаем типа номера квартир вместо прихожка?

**Comment by op-hui** [comment]
> может сделаем типа номера квартир вместо прихожка?

Да, сейчас идея крутится вот какая, сделать модель дома, в котором есть 5 этажей.
на каждом этаже по 4 хаты + общая локация лестничная площадка.

Если Анонов будет столько. что они перенаселят дом - создать дом рядом, связать их двором.
Как то так.

**Comment by copyright2015** [comment]
![xmkvy_vk5dk](https://cloud.githubusercontent.com/assets/14098252/9736133/5cf3aea8-5661-11e5-9719-eb139759853a.jpg)

**Comment by op-hui** [comment]
WON'T FIX
