### ISSUE TITLE
Выделять НПЦ в локации

### ISSUE THREAD

**Issue by op-hui** [op-hui/mu2ch#30]
Сделать цветовую дифференциацию между просто объектами и объектами NPC

**Comment by op-hui** [comment]
Если я ничего не путаю, то это нужно делать через метод return_appearance https://github.com/evennia/evennia/blob/master/evennia/contrib/extended_room.py#L212 как пример.

Дока по раскрашиванию https://github.com/evennia/evennia/wiki/Understanding-Color-Tags

**Comment by copyright2015** [comment]
решили что темно зеленый пока самый норм
![2015-09-09_1-21-20](https://cloud.githubusercontent.com/assets/14098252/9745210/2e5ae0da-5692-11e5-9692-b711aa5cafc0.jpg)

**Comment by copyright2015** [comment]
желтый тоже ничего
![2015-09-09_1-41-15](https://cloud.githubusercontent.com/assets/14098252/9745466/e4cdc44e-5693-11e5-8be2-59346dc041fa.jpg)

**Comment by copyright2015** [comment]
комнаты пересоздавать не нужно, только неписей. или задавать в ручную @set имяNPC/npc = True, тогда они начнут светиться

**Comment by op-hui** [comment]
отлична
