### ISSUE TITLE
Интерьер локации

### ISSUE THREAD

**Issue by op-hui** [op-hui/mu2ch#31]
Локации нужно разнообразить деталями.

Например описание локации

Ты видишь невзрачную комнату с **картиной** на стене

Пользователю может посмотреть на картину в этой локации:

посмотреть картина:

```
Ты видишь картину, на которой изображен утонувший кораблик и хихикающий Тесла
```

По утверждениям разработчика evennia, такой функционал уже реализован в https://github.com/evennia/evennia/blob/master/evennia/contrib/extended_room.py

**Comment by copyright2015** [comment]
Есть там такая фича. Но эти детали явно не показаны, когда смотришь. Если только знаешь их имя, только тогда можно посмотреть.
Есть два варианта. Либо мы в описании будем в ручную подкрашивать эти детали. Либо допилим и сделаем что-то типа 
You see: бла бла
Details: бла бла
Команда Look там уже запилена, нужно будет запилить return_appearance()

**Comment by op-hui** [comment]
По идеи нужно сделать три-четыре типа деталей
1. Самые простые, что бы не перегружать локации списком объектов находящихся в ней, деталь выделяется цветом в описании комнаты, например:

> смотреть

Вы находитесь в комнате, на стене висит **картина**

> смотреть картина

На картине изображен черный квадарат
1. Тип детали объект, но не отображающийся в списке объектов в комнате:

> смотреть 

Вы стоите в комнате, в углу располагается **сундук**

> смотреть сундук

Пыльный старый сундук

> положить объект = сундук

Вы положили объект в сундук
1. Деталь рассчитанная на пытливый ум, деталь никак не выделяется в описании

> смотреть

На столе лежит листок

> смотреть листок

Иди на коридор, там лолли
1. Самый сложный тип детали, например каждый день на столе в определенной локации появляется листок (если его там нет)

> смотреть

Вы видите стол. На столе лежит листок

> взять листок

Вы взяли листок

> смотреть

Вы видите стол

> смотреть листок

Завтра в столовке будет картоха

Для первого релиза сойдет первый тип детали.

**Comment by copyright2015** [comment]
Они все здесь первые, лол, но не суть.

копну в этом направлении седня

**Comment by copyright2015** [comment]
Вот кароче. Автоматически определяет детали, совпадающие с текстом описания.
Например : 
"комната в ней картина". если будет создана деталь с названием "картина", она подсветится в тексте описания желтым цветом. 
![2015-09-09_15-40-17](https://cloud.githubusercontent.com/assets/14098252/9758555/2a46c884-5709-11e5-8d15-6f4b78d9289b.jpg)
![2015-09-09_15-50-17](https://cloud.githubusercontent.com/assets/14098252/9758789/85598d28-570a-11e5-9a24-cf250ad314f3.jpg)

**Comment by copyright2015** [comment]
@detail деталь = На картине туннущий кораблик и смеющийся тесла
@dig комната:extended_room.ExtendedRoom

**Comment by copyright2015** [comment]
размышляю на тему, запишу пока не забыл

думаю для второго и третьего типов, будем задавать свойства 

в первом случае с сундуком:
hide_type = desc_visible

во втором с листком:
hide_type = desc_invisible

и при осмотре не будем их выводить в секцию You see:

с третьим не придумал пока
