### ISSUE TITLE
"Системные" сообщение

### ISSUE THREAD

**Issue by op-hui** [op-hui/mu2ch#33]
Перевести системные сообщения в самом движке, типа:

Exits: - Выходы
Игрок arrives from Прихожка - Игрок пришел из Прихожка

И т.д. и т.п.

**Comment by copyright2015** [comment]
Так, перевод есть. Найденные баги пишем сюда. Найденные не корректности в переводе пишем сюда. Я правлю. Или сами правите)))

**Comment by op-hui** [comment]
Появление игрока в локации:
copyright arrives to Коридор from Прихожка.

**Comment by op-hui** [comment]
Я глубоко не копал, но на вскидку, у меня пропали имена выходов, когда я начал использовать вместо DefaultRoom, класс Room в генерации зданий, этажей и квартир.

**Comment by copyright2015** [comment]
Создал комнату типа typeclasses.rooms.Room, от которого нужно наследоваться. Создал выходы. Вроде все на месте.

**Comment by copyright2015** [comment]
перевел эти хрени - copyright arrives to Коридор from Прихожка.
