### ISSUE TITLE
Релиз первого маня мирка

### ISSUE THREAD

**Issue by op-hui** [op-hui/mu2ch#34]
Вводная:

Есть общая локация двор, общая для всех игроков, они в ней респаунятся.
Для каждого игрока выделяется хата, в которой находятся его мамка и лысый батя. Хата состоит из 5-7 локаций, Кухня, Сортир, Сычевальня, Ванная.
Дом Хрущевки, состоят из подъезда, этажей, и собственно квартиры. Игроки являются соседями друг друга, в незаселенных ещё комнатах могут жить соседи NPC, либо быть просто не заселенной.  

Если для нового игрока не хватает построенной хаты, сервер достраивает дополнительный дом ко двору, куда заселяет игрока

NPC: Твоя Мамка, Лысый батя - с уникальными описаниями биографий, Лолли которая отдается за конфеты и трюфеля в общей локации двор. Продавщицы в аптеке. Соседи (быдланы, с личинкой, бабка, etc). Мамка любит подарки, а Лысый батя внимательно слушает как игрок его называет.

Смерть игрока:
Игроки могут убивать друг друга, или умереть от выхода из окна своей сычивальни.
Для того что бы убить игрока, нужно иметь оружие в своей руке. 
Примеры предметов, которые можно использовать как оружие:
Картонный нож - одноразовое оружие, может достать его на кухне в своей хате, респаун после использования - через в N минут.
Банка с кислотой - трехразовое оружие, для ее создания, нужно взять банку с кухни, спиздить деньги с одежды бати (респаун каждые 3 минуты), зайти в одну аптеку купить водород.
Зайти в другую локацию с другой аптекой купить серу и водород. из ингредиентов получить серную кислоту, банки её хватает на три убийства

Общая локация в которой происходит респаун игроков вошедших в игру или после смерти называется Двор, она соединена с домами. Так же из этой локации есть выход в общую локацию, в которой игрок игрока убить не может. 

Будет сделана специальная команда, по которой игрок сможет сменить свои убеждения и религию (предоставляется выбор). На основании этого выбора, локация где игроки не могут убивать друг друга (даже имея оружие в руке), будет иметь разные описания (Эдем,Шабала,Нирвана,Ебаное ничего,42,etc)

Доходы Анона: (каждые игровые сутки, анону мамка дает на еду), или воровство с трупа.

**Comment by op-hui** [comment]
[Список открытых багов для перворого релиза](https://github.com/op-hui/mu2ch/milestones/%D0%9F%D0%B5%D1%80%D0%B2%D1%8B%D0%B9%20%D1%80%D0%B5%D0%BB%D0%B8%D0%B7)

**Comment by op-hui** [comment]
Обыграть то что игрок появляется в общей локации двор можно так:

Анону мамка поручила сходить за хлебушок, в инвентаре у анона хлебушек.
Первый квест анона, этой найти свою мамку и хату (можно посмотреть в команде статус) и отдать ей хлебушек

**Comment by op-hui** [comment]
Mu2ch - первый релиз онлайн текстовой (inb4 дальше не читал) MMORPG по мифологии имиджборд (inb4 раки не нужны, сейчас не 2009).

_Кратко: 6 с половиной анонов собрались 2 недели назад и спустя 300 комитов запилили первый релиз маня игры на базе свободного движка evennia. Наш код открыт https://github.com/op-hui/mu2ch, разработка децентрализована._

Сервер: http://mu2ch.epac.to:8000/webclient

**Прежде чем войти в игру, прочитай краткий гайд как нагибать:**

Игра представляет собой набор локаций, статичных, так и динамичных, из каждой локации есть выходы. Что бы выйти в нужном направлении, достаточно набрать имя выхода. Осмотреть локацию можно командой **смотреть**, команда **смотреть Леночка** - покажет что из себя представляет Леночка или другой предмет вместо неё.

После входа в игру, ты оказываешься в общем дворике, на юге виднеется аптека, на западе дома, на севере зона свободная от убийств лол. Во дворике стоит Леночка, она приехала из деревни и готова отдастся за коробку шоколадных конфет. А если у тебя есть еще и трюфели - пустит на задний двор. Заговорить с Леночкой можно с помощью команды **talk Леночка**

Так же после входа в игру тебе сообщается твой адрес прописки, посмотреть который так же можно через команду **статус**.

Найдя свою хату, ты можешь обнаружить на кухне мамку и картонный нож (оружие коим можно единоразово убить другого анона). В сортире окопался лысый батя, только не говори ему что он лысый лол.

В игре присутствует игровая валюта - интернеты. Периодически тебе их выдает мамка, либо ты можешь невозбранно убивать других игроков, и пиздить интернеты с их трупов лол.

Общаться в игре можно через команду **сказать** или **"**. Например: "сап

К югу от общего дворика можно найти аптеку, в аптеке продаются вещества, употребив которые с помощью команды **юзать** или **употребить** ты начинаешь вести себя странно, например выходить в окна. С Аптекаршой можно вступить в диалог командой **talk Аптекарша**

Так же Аптекарша продает ингредиенты для создания трехразового оружия, банкой серной кислоты. Собрать их воедино из можно через команду **алхимия**. 

Что бы использовать оружие, нужно **взять** его к себе в **инвентарь**, и потом использовать команду **одеть** - что бы взять в руки, такая вот команда блеять.

Убить другого игрока можно с помощью команды **убить %ИгрокНейм%**.  После убийства игрока, появляется его труп, лутать который можно с помощью команды: **взять %ИгрокНейм% = "вещь" или"все"**. 

Так же анон может объединяться в группы с помощью команды **группа**. У группы есть лидер, куда он, туда и его команда.  

Если игрок умирает, он просыпается на лекции.

По всем доступным командам, есть помощь, можно набрать **help** или **help** команда.

Подбирать предметы можно с командой **взять предмет**. 
Говорить с npc: **talk NpcName**

Это первый релиз, рандомных анонов из интернетика, в нем есть баги, отписывайтесь в тред, а лучше сразу сюда https://github.com/op-hui/mu2ch/issues

**Мы коордиринуемся в конфе mu2ch@conference.jabber.ru и ищем новые таланты в наши ряды. Поможем, обучим, нужны говнокодеры и графоманы и просто люди умеющие в игровой баланс**

Второй релиз состоится аж 16 октября. Рабочий процесс строится через ишуи на гитхабе: https://github.com/op-hui/mu2ch/issues

Гайды как создавать NPC, поднимать свой сервер, вникнуть в процесс разработки можно посмотреть в нашей вики https://github.com/op-hui/mu2ch/wiki

Основной тред в /gd http://2ch.hk/gd/res/186410.html

**Comment by copyright2015** [comment]
Можно лутать трупы при помощи команды взять %ИгрокНейм% = "вещь" или "все"

**Comment by copyright2015** [comment]
Есть примитивный крафт. Пока есть два рецепта. Бутылка с кислотой и Бейлис.
Команда - алхимия ингредиент1+ингредиент2+ингредиентN+...
Плюс обязателен.

**Comment by op-hui** [comment]
зарелизили лол
