### ISSUE TITLE
Команда сказать и talk

### ISSUE THREAD

**Issue by op-hui** [op-hui/mu2ch#35]
Нужно объединить эти команды, если у команды есть аргумент и он НПЦ - то выполняется разговор с NPC, иначе, обычное поведение команды "сказать

**Comment by copyright2015** [comment]
У команды "talk" уже есть варианты "говорить" и "ск". Я думаю, что сказать кому-то и говорить-с кем-то немного разные вещи.

**Comment by op-hui** [comment]
Полностью, но игрока это вводит в когнитивный диссонанс
мне код "сказать" представляется так:

```
если второй_аргумент == разговаривющий_НПЦ
   self.execute_cmd("talk npc")
else
   self.execute_cmd("сказать")
```

**Comment by copyright2015** [comment]
будет примерно так

```
message = self.caller.serch(args, location=caller.location)
if message:
     if inherits_from(npc):
           делать код команды talk
else: 
    делать код команды сказать
```

**Comment by copyright2015** [comment]
пойду запилю

**Comment by copyright2015** [comment]
готово, теперь можно начать диалог так:

```
"имя_npc

или

сказать имя_npc
```

если такого npc нет , ты просто говоришь его имя
если в локации несколько неписей с одним именем будет выбран первый попавшийся
