### ISSUE TITLE
Группа игроков. Команда следовать

### ISSUE THREAD

**Issue by op-hui** [op-hui/mu2ch#37]
Позволяет следовать за игроком, если он передвигается.
Игрок за которым следуют должен согласиться на это (добавить в свою группу)
Админы могут следовать за кем угодно, без включения в группу

**Comment by copyright2015** [comment]
нужны следующие команды для присоединяющегося:
следовать игрок_нэйм - следовать за игроком
следовать<без аргументов> - перестать следовать

для лидера:
дропнуть игрок_нейм - выкинуть из группы

**Comment by copyright2015** [comment]
Запилил команды, следование по локациям

Завтра буду наверно делать команду "группа" - что бы смотреть кто в группе.

**Comment by copyright2015** [comment]
а лучше вынесу эту инфу в команду "статус"
