### ISSUE TITLE
Смерть игрока

### ISSUE THREAD

**Issue by op-hui** [op-hui/mu2ch#41]
Реализовать команду убить:

Команда убить ИмяИгрока должна убивать Игрока
После убийства переносить игрока в 1-Limbo

**Comment by copyright2015** [comment]
На данный момент реализовано:
Команда "убить Имя_игрока" - можно убивать только игроков, только если в руках оружие.
Добавление количества фрагов и количества смертей. убил - тебе плюс фраг, тебя убили тебе плюс количество смертей.
Также добавлен сброс эффектов которые есть на персонаже.
Реализовано разрушение оружия про потере всех очков запаса прочности.
Жертва после убийства телепротируется в Limbo.

Работаю и думаю над:
Дроп, и лутание трупа.
Команда "лутать Имя_трупа"
Возможно имеет смысл сделать пока просто выброс в локацию шмота игрока при смерти.

как убить игрока:

```
@create нож:weapons.Knife
или
@create банка:weapons.AcidBottle

одеть нож
или
одеть банка

ищем жертву

Когда нашили 
убить имя_жертвы
...
PROFIT
```

**Comment by copyright2015** [comment]
теперь вооруженные игроки в локациях подсвечиваются красным

**Comment by copyright2015** [comment]
возможен самовыпил, и он детектиться командой.

```
убить свое_имя - самовыпил.
```

В локации появиться сообщение - имя_игрока самовыпилился.

**Comment by copyright2015** [comment]
как убить игрока:

@create нож:weapons.Knife
или
@create банка:weapons.AcidBottle

одеть нож
или
одеть банка

ищем жертву

Когда нашили: 
убить имя_жертвы

лутеам труп жертвы:
лут имя_игрока

если сам сдох то можно найти свой труп и залутать его:
лут 2-свое_имя 
...
PROFIT
