### ISSUE TITLE
Респаун предмета по таймеру.

### ISSUE THREAD

**Issue by op-hui** [op-hui/mu2ch#42]
Нужна возможность привязать респаун предмета по таймеру в какой либо определенной локации (в идеале, это список локаций, из которых выбирается случайная)

Поведение:
Предмет респаунится. Если он исчезает из игры, например его удаляют. Он опять респаунится (но не чаще чем раз в интервал).

Если предмет уже есть, то он не респаунится заново

**Comment by copyright2015** [comment]
Запускать скрипт пока нужно в самой игре.
Каждые 30 секунд он проверяет объекты, заданные в инструкции, и если один из них был уничтожен, создает новый согласно инструкции. 
Для этого нам нужна комната

```
@dig makaba

@tel makaba

запуск 
@script here = item_respawn.RespawnHandler

остановка
@script/stop here = spawn_script
```

Внутри этой комнаты мы создали скрипт.
Скрипт будет писать сюда логи, и можно мониторить создание объектов, находясь в этой комнате.
Работа скрипта не ограничивается объектом к которому он привязан, в нем только появляются логи.
У скрипта есть инструкции: что создать, где создать, сколько объектов должно быть в мире.
Пока все необходимые объекты находятся в мире, скрипт ничего не делает.
Скрипт не падает при перезапуске сервера.
Скрипт не падает при ошибках в коде.
