### ISSUE TITLE
Предметы которые можно использовать как оружие

### ISSUE THREAD

**Issue by op-hui** [op-hui/mu2ch#43]
Для первого релиза, нам нужно сделать предметы убийства.

Если у игрока в руке есть предмест убийства, он может убить другого игрока командой: убить.

У предмета должно быть количество использований, которое можно задать, после N убийств этим предметом, он исчезает.

**Comment by copyright2015** [comment]
Фундамент Заложен
![2015-09-12_0-45-24](https://cloud.githubusercontent.com/assets/14098252/9823373/ae6a9b10-58e7-11e5-8f47-ce17e34c268d.jpg)

**Comment by copyright2015** [comment]
+ появилась такая идея пока писал базовый класс
![2015-09-12_1-05-24](https://cloud.githubusercontent.com/assets/14098252/9823810/73babf92-58ea-11e5-839f-e786d423d47b.jpg)

**Comment by copyright2015** [comment]
есть еще такая идея
![2015-09-12_1-08-21](https://cloud.githubusercontent.com/assets/14098252/9823864/cc8ff326-58ea-11e5-9b33-9f134bdfe8cf.jpg)

**Comment by op-hui** [comment]
Насчет ТТ - не понятно пока как его интегрировать в наш первый маня-релиз.
Нужна прохладная про то как его добыть...

Алсо так же предлагаю после убийства, прибавлять в профиле игрока количество фрагов.

**Comment by copyright2015** [comment]
про тт это просто на будущее, как идея с комплектующими к оружию

**Comment by Semen-201** [comment]
Обязательно кого-то убивать? Много же просто отмудохать, и достаточно кулаков в начале. Я бы сделал акцент на взаимодействия с игроками, а не организацию массовых друг-друговыпилов.

**Comment by op-hui** [comment]
Убивать обязательно, т.к. это элемент доминирования в ММОРПГ.
Все оружие в первом релизе будет одноразовым, или трехразовым, после этого, его нужно заново добывать. Сделаем респауны того, с помощью чего можно собрать оружие - раз в 45 в минут, или в полчаса. 
Убийства будут, но довольно редкие

**Comment by copyright2015** [comment]
Вроде оружие работает как задумано, закрою этот
