### ISSUE TITLE
Алхимия

### ISSUE THREAD

**Issue by op-hui** [op-hui/mu2ch#44]
Сделать простую алхимю.

Реализовать команду "алхимия", которая соединяет объекты, если объекты можно соединить по алихимческим правилам игры - появляется новый объект.

**Comment by copyright2015** [comment]
СДелана команда "алхимия"
Реализована система рецептов.
первые рецепты:

```
алхимия сера+водород+бутылка  - бутылка с кислотой
алхимия кофе 3в1+водка  - Бэйлис
```

последовательность компонентов произвольная.
компоненты являются простыми объекта. Все привязано к названию объекта.
