### ISSUE TITLE
Руки персонажа и команда одеть(wear)

### ISSUE THREAD

**Issue by copyright2015** [op-hui/mu2ch#49]
Необходимо добавить новый контейнер к нашим персонажам - руку или руки пока что. Именно персонажам. Также нужна команда - одеть [имя_объекта], чтобы можно было класть предметы в руку, любые, включая оружие. Либо пока только оружие. Оружие имеет атрибут self.db.is_weapon = True. Прошу подумать на тему, нужно ли, когда смотришь на игрока, отображать что у него в руках. Я думаю что нужно, а вы?

**Comment by copyright2015** [comment]
Думаю нужно еще запилить команду "снять"

**Comment by op-hui** [comment]
Да, я вообще думал, что персонажей с оружием в руках в локации нужно выделять красным цветом лол (сделать опционально? если есть нож - то красным, если банка с серной кислотой - не выделять на фоне других игроков)

Да, если смотреть на игрока, то можно увидеть что на нем сейчас

Снять - тоже нужно.

Для первого релиза, думаю хватит одной руки лол

**Comment by copyright2015** [comment]
Теперь у персонажа есть руки - self.db.hands тип объект
Получить содержимое рук - self.db.hands.contents, тип список объектов

```
Чтобы положить в руку объект, он должен быть в инвенторе. Команда - одеть имя_объекта
Команда "снять" убирает из рук объект в инвентарь.
Команда "@руки" дает твоему персонажу руки если их нет и доступна только билдерам.
Когда сморишь на игрока и у него в руках что есть, то появляется дополнительное описание "В руках : имя_объекта".
```

Подсветки игрока с оружием пока нет.
Думаю будем подсвечивать игрока с любым оружием.

**Comment by copyright2015** [comment]
Нужно сделать подцветку вооруженного игрока на локации

**Comment by copyright2015** [comment]
Теперь вооруженный игрок обозначен красным цветом + чтобы заменить предмет в руках достаточно одеть новый
