### ISSUE TITLE
Религия

### ISSUE THREAD

**Issue by op-hui** [op-hui/mu2ch#50]
Введем команду, которая позволяет менять религию персонажа.
Для начала попробуем

Буддизм
Христианство 
Сатанизм

В зависимости от религии локация с PVE будет отображаться по разному, типа Рай,Нирвана,Чистилище,ЕБАНОЕ НИЧЕГО,etc

**Comment by copyright2015** [comment]
Добавил персонажу список доступных религий. не как атрибут в бд, а как просто поле класс, то есть чтобы были доступны новые религии персонажа пересоздавать не нужно, достаточно перезапустить сервер.

Добавил команду "религия" или "уверовать"

```
религия<без аргументов> - показать список доступных религий

религия навание_религии - сменить религию

религия отречься - стать атеистом.
```
