### ISSUE TITLE
Труп после смерти

### ISSUE THREAD

**Issue by op-hui** [op-hui/mu2ch#67]
В идеале должно быть так:

Игрок умирает в локации - там остается его труп
В труп можно посмотреть, взять из него содержимое

Через 3 минуты труп пропадает, вместе с инвентарем в нем

**Comment by copyright2015** [comment]
Когда игрока убивают он оставляет труп в локации где умер и отправляется в Limbo
В труп переносяться все его шмотки.
Труп подсвечивается в локациях цветом darck cyan
Выглядит имя_игрока(труп)

```
посмотреть - смотреть имя_игрока
лутать труп - лут имя_игрока
                      лутать имя_игрока
                      шмонать имя_игрока
                      loot имя_игрока
```

Лутать можно только трупы. Лутаются сразу все вещи.
Труп исчезает по истечении 3 минут после смерти игрока вместе со всем шмотом.
теперь у Character`a есть метод at_die(). Вызвав его персонаж "умирает".
класс трупа Corpse унаследован от Character. по факту труп- как непись, только мертвый лол.
То что было у игрока в руках переноситься в инвентарь трупа. тоесть если ты убил лоха с ножем в руках, получаешь его нож.
У трупа рандомное описание - типа "Бренное тело pupkin" или "всё что осталось от pupkin" и т.д.

**Comment by op-hui** [comment]
После того, как труп исчез, в локацию, где он исчез нужно послать нотификацю
"Прах игрока Семёна исчезает у тебя на глазах"

**Comment by copyright2015** [comment]
сделано

**Comment by copyright2015** [comment]
Перепилить лут и команду взять под следующий формат
взять <объект><объект внутри первого объекта или все>

**Comment by copyright2015** [comment]
предлогаю сделать так

взять твоя мамка = мелось
взять твоя мамка = все

**Comment by copyright2015** [comment]
или
взять твоя мамка.мелочь
взять твоя мамка.все

**Comment by copyright2015** [comment]
команда взять работает теперь так:

```
взять говно - работает так же как и раньше, берешь говно если оно есть на локации
взять сундук = говно - берешь говно из сундука, если оно там есть 
взять труп = говно - берешь говно с трупа, если у него было говно
```

У сундука должен быть атрибут self.db.is_storage = True
А труп должен быть унаследован от класса Corpse.

**Comment by copyright2015** [comment]
любой труп разлагается через 3 минуты
