### ISSUE TITLE
Игровые деньги

### ISSUE THREAD

**Issue by op-hui** [op-hui/mu2ch#69]
Концепт в идеале:

Деньги можно тратить в аптеке на вещества и химию для создания оружия.
Деньги можно красть из трупа, это объект с номиналом.
Можно передать часть денег другому игроку, npc
Деньги игроку дает мамка, каждый игровой день, как только его увидит.

**Comment by copyright2015** [comment]
новые формулировки команд

```
дать деньги = имя_объекта - дать все деньги которые у тебя есть объекту.
дать деньги 20 = имя_объекта - дать 20 денег объекту.
взять имя_объекта = деньги - взять все деньги из объекта(is_storage or is_corpse)
взять имя_объекта = все - взять все вещи и все деньги.
взять имя_объекта = деньги 20 - взять 20 денег из объекта(is_storage or is_corpse) 
```

команда статус показывает количество денег.

Далее нужно сделать что бы мамка давала деньги анону, раз в игровые сутки. и сделать описание сколько в хранилище денег(если объект is_storage).

**Comment by copyright2015** [comment]
Теперь у мамки есть 2 новых атрибута:

```
self.db.last_payout - последняя выплата денег, для определения момента выплаты
self.db.is_mom - для поиска на локации. что бы не зависеть от имени мамки.
```

когда игрок заходит в комнату, идет проверка наличия мамки. Если он ее встречает, и с момента последней выплаты прошло 24 часа, то мамка дает анону 10 денег.
