### ISSUE TITLE
Аптекарша

### ISSUE THREAD

**Issue by op-hui** [op-hui/mu2ch#71]
По готовности #53 ишуя, запилить на его базе Аптекаршу в аптеке.
Она должна торговать 

Веществами - 15 единиц денег
Сера - 3 единицы денег

Респаун веществ должен происходить спустя от случайного числа между 15 секундами и 120

**Comment by copyright2015** [comment]
Создать аптекаршу

```
@create/drop Аптекарша:npc.Druggist
```

как только создали аптекаршу у нее нет веществ и товаров, просто еще не завезли лол)
максимум через 120 секунд они будут.
таймер берет рандом то 12 до 120 секунд

**Comment by copyright2015** [comment]
у игрока теперь есть self.db.money. Тестово при создании дается 100 интернетов
